### ISSUE TITLE
visualize

### ISSUE THREAD

**Issue by feichaiyu** [xnowbzhao/PU-SSAS#1]
Great job! Also, I'm curious about how to visualize .xyz files. Especially the testing results on the KITTI dataset mentioned in the paper, how was that done?

**Comment by xnowbzhao** [comment]
Hi, the visualization results are obtained by MeshLab.

**Comment by feichaiyu** [comment]
> Hi, the visualization results are obtained by MeshLab.

Hey, thanks for getting back to me. I've used MeshLab to visualize .xyz files. I'm curious, did you use the ShapeNet dataset to test the model on the KITTI dataset? How did you go about it, and where can I find examples from KITTI? I'm not too familiar with the Self-Supervised algorithm.

**Comment by xnowbzhao** [comment]
"did you use the ShapeNet dataset to test the model on the KITTI dataset?"
I train the model on ShapeNet and test the model on KITTI.

"where can I find examples from KITTI?"
you can search "Semantic Kitti" to download the dataset.

**Comment by feichaiyu** [comment]
> "did you use the ShapeNet dataset to test the model on the KITTI dataset?" I train the model on ShapeNet and test the model on KITTI.
> 
> "where can I find examples from KITTI?" you can search "Semantic Kitti" to download the dataset.

PU-SSAS works really well for upsampling point clouds of real objects. I was wondering if it can also be used for upsampling all the point clouds obtained from lidar scans. I tested it with the KITTI velodyne_raw data and found that the results were quite poor. I'm not sure why this is the case. Can anyone help me figure this out?

![image](https://github.com/xnowbzhao/PU-SSAS/assets/47424844/3c68988d-d031-4180-82ac-7c3aabf1c56f)
the left side is the original point cloud, and the right side is the processed point cloud

**Comment by xnowbzhao** [comment]
Hi, The propose seed generation method does not handle this situation well and we are focusing on improving it.

**Comment by feichaiyu** [comment]
> Hi, The propose seed generation method does not handle this situation well and we are focusing on improving it.

Hey, thanks for getting back to me. Looking forward to seeing your new work!
